[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[theme]
base = "dark"
primaryColor = "#00a67e"
backgroundColor = "#111111"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#e9e9e9"
